---
name: close-pr

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  # PR close時にCIが出したPRをcloseする
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          repo-name: ${{ github.event.pull_request.head.repo.full_name }}
